# Generated by Django 4.2.7 on 2023-12-28 15:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('det', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_title', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime(2023, 12, 28, 15, 40, 45, 996038, tzinfo=datetime.timezone.utc))),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('food', 'Food'), ('utilities', 'Utilities'), ('transportation', 'Transportation'), ('entertainment', 'Entertainment'), ('clothing', 'Clothing'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('housing', 'Housing'), ('technology', 'Technology'), ('travel', 'Travel'), ('gifts', 'Gifts'), ('subscription', 'Subscription'), ('miscellaneous', 'Miscellaneous')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
