# Generated by Django 4.2.7 on 2024-01-08 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('det', '0008_expense_deleted_expense_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 8, 36, 8, 503461, tzinfo=datetime.timezone.utc)),
        ),
    ]
