# Generated by Django 4.2.7 on 2024-01-08 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('det', '0009_remove_expense_deleted_remove_expense_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('delete', 'Delete'), ('trash', 'Trash')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 13, 25, 43, 325009, tzinfo=datetime.timezone.utc)),
        ),
    ]
