# Generated by Django 4.2.7 on 2024-01-08 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('det', '0010_expense_status_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 14, 18, 35, 844070, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('delete', 'Delete'), ('trash', 'Trash')], default='published', max_length=10),
        ),
    ]
