# Generated by Django 4.2.7 on 2024-01-08 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('det', '0011_alter_expense_date_alter_expense_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 8, 14, 18, 44, 330333, tzinfo=datetime.timezone.utc)),
        ),
    ]
